### ISSUE TITLE
loadui module cannot be read

### ISSUE THREAD

**Issue by bagomot** [vitalfadeev/d-coder-ui#1]
source\ui\package.d(50,15): Error: module `loadui` is in file 'ui\loadui.d' which cannot be read.

ui\loadui.d file is missing.

**Comment by vitalfadeev** [comment]
> source\ui\package.d(50,15): Error: module `loadui` is in file 'ui\loadui.d' which cannot be read.
> 
> ui\loadui.d file is missing.

Yes.
master branch is outdated, not supported.
It contains devepoment code, for access from other machines.

I working under GUI on local machine and will public project to the  https://github.com/d-gui
All code will be moved to the https://github.com/d-gui

**Comment by vitalfadeev** [comment]
> source\ui\package.d(50,15): Error: module `loadui` is in file 'ui\loadui.d' which cannot be read.
> 
> ui\loadui.d file is missing.

Don't try compile.
Because It not completted.
I working under text rendering in GL3.

Beta will be after 1 month.

Project will be completted afted 6 monthes.

**Comment by bagomot** [comment]
OK. It’s to wait so long. I need to make a GUI now.
I would even do on opengl, but I encountered an error suppressing the opening of the console on windows x64 ("/subsystem: windows" "/entry: mainCRTStartup").

In any case, success! If you need Windows tests, please contact me.
